# Generated by Django 5.2.9 on 2026-01-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='iframe_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
