# Generated by Django 5.2.9 on 2026-01-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_destination_iframe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='iframe_url',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
