# Generated by Django 5.0.6 on 2026-02-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_destination_iframe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_step',
            field=models.CharField(blank=True, help_text='Current onboarding step', max_length=50, null=True),
        ),
    ]
