# Generated by Django 5.2.9 on 2026-02-17 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_has_completed_onboarding_user_onboarded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Short teaser for cards and lists.', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('featured', 'Featured'), ('community', 'Community'), ('workshop', 'Workshop'), ('recap', 'Recap')], default='featured', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past Event')], default='upcoming', max_length=20)),
                ('is_featured', models.BooleanField(default=True, help_text='Show in homepage events carousel.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['-is_featured', '-start_datetime'],
            },
        ),
    ]
